export enum GameStateType {
    IDLE = 'IDLE',
    WAITING_ON_SECOND_PLAYER = 'WAITING_ON_SECOND_PLAYER',
    MOVE_INTO_POSITION = 'MOVE_INTO_POSITION',
    GIVE_INSTRUCTIONS = 'GIVE_INSTRUCTIONS',
    GAME_START = 'GAME_START',
    PLAYING = 'PLAYING',
    GAME_END = 'GAME_END',
    EXPLANATION = 'EXPLANATION'
}
